# Form implementation generated from reading ui file 'd:\Proyectos\SISTEMA-OSEO-EXPERTO-API\sistema_oseo.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 1000))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(205, 222, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(248, 249, 253);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1071, 51))
        self.label.setStyleSheet("font: 87 18pt \"Poppins Black\";\n"
"background-color: rgb(90, 129, 250);\n"
"background-color: rgb(90, 129, 250);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 620, 71, 16))
        self.label_3.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 12pt \"Poppins Medium\";")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_3.setObjectName("label_3")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(460, 70, 251, 31))
        self.label_17.setStyleSheet("font: 75 14pt \"Poppins\";\n"
"color: rgb(31, 31, 31);")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(540, 130, 20, 401))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(600, 120, 351, 21))
        self.label_20.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(150, 280, 351, 31))
        self.label_21.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(140, 390, 351, 21))
        self.label_22.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(590, 280, 351, 21))
        self.label_23.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(-10, 770, 1121, 161))
        self.scrollArea_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(90, 129, 250);\n"
"border-color: rgb(166, 166, 166);")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1119, 159))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_26 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_26.setGeometry(QtCore.QRect(820, 10, 101, 21))
        self.label_26.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Poppins Medium\";")
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_27.setGeometry(QtCore.QRect(450, 10, 151, 21))
        self.label_27.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Poppins Medium\";")
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_28.setGeometry(QtCore.QRect(90, 10, 81, 21))
        self.label_28.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 12pt \"Poppins Medium\";")
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_29.setGeometry(QtCore.QRect(90, 40, 91, 21))
        self.label_29.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Poppins light\";")
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_30.setGeometry(QtCore.QRect(90, 70, 81, 21))
        self.label_30.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Poppins light\";")
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_31.setGeometry(QtCore.QRect(90, 100, 121, 21))
        self.label_31.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Poppins light\";")
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_32.setGeometry(QtCore.QRect(430, 40, 181, 21))
        self.label_32.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_33.setGeometry(QtCore.QRect(400, 70, 251, 21))
        self.label_33.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_33.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_34.setGeometry(QtCore.QRect(820, 70, 171, 21))
        self.label_34.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Poppins light\";")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_35.setGeometry(QtCore.QRect(820, 40, 161, 21))
        self.label_35.setStyleSheet("color: rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Poppins light\";")
        self.label_35.setObjectName("label_35")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(240, 170, 151, 21))
        self.label_18.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.filtradoNombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.filtradoNombre.setGeometry(QtCore.QRect(230, 620, 181, 21))
        self.filtradoNombre.setText("")
        self.filtradoNombre.setObjectName("filtradoNombre")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 560, 171, 21))
        self.label_10.setStyleSheet("font: 75 14pt \"Poppins\";\n"
"color: rgb(31, 31, 31);")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.onClickBuscar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.onClickBuscar.setGeometry(QtCore.QRect(450, 620, 91, 23))
        self.onClickBuscar.setObjectName("onClickBuscar")
        self.TextDiagnostico = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.TextDiagnostico.setEnabled(True)
        self.TextDiagnostico.setGeometry(QtCore.QRect(640, 600, 241, 121))
        self.TextDiagnostico.setObjectName("TextDiagnostico")
        self.enviarDatos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enviarDatos.setGeometry(QtCore.QRect(670, 430, 191, 23))
        self.enviarDatos.setObjectName("enviarDatos")
        self.inputpostuser = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputpostuser.setGeometry(QtCore.QRect(280, 130, 181, 21))
        self.inputpostuser.setText("")
        self.inputpostuser.setObjectName("inputpostuser")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(170, 200, 291, 51))
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_r1_0 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_r1_0.setGeometry(QtCore.QRect(190, 20, 82, 17))
        self.radioButton_r1_0.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r1_0.setObjectName("radioButton_r1_0")
        self.radioButton_r1_1 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_r1_1.setGeometry(QtCore.QRect(50, 20, 31, 17))
        self.radioButton_r1_1.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r1_1.setObjectName("radioButton_r1_1")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 310, 301, 51))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_r2_1 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_r2_1.setGeometry(QtCore.QRect(50, 20, 31, 17))
        self.radioButton_r2_1.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r2_1.setObjectName("radioButton_r2_1")
        self.radioButton_r2_0 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_r2_0.setGeometry(QtCore.QRect(190, 20, 41, 17))
        self.radioButton_r2_0.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r2_0.setObjectName("radioButton_r2_0")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(180, 420, 291, 51))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_r3_1 = QtWidgets.QRadioButton(parent=self.groupBox_3)
        self.radioButton_r3_1.setGeometry(QtCore.QRect(50, 20, 82, 17))
        self.radioButton_r3_1.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r3_1.setObjectName("radioButton_r3_1")
        self.radioButton_r3_0 = QtWidgets.QRadioButton(parent=self.groupBox_3)
        self.radioButton_r3_0.setGeometry(QtCore.QRect(180, 20, 82, 17))
        self.radioButton_r3_0.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r3_0.setObjectName("radioButton_r3_0")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(630, 169, 281, 61))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_r4_1 = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButton_r4_1.setGeometry(QtCore.QRect(50, 20, 82, 17))
        self.radioButton_r4_1.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r4_1.setObjectName("radioButton_r4_1")
        self.radioButton_r4_0 = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButton_r4_0.setGeometry(QtCore.QRect(190, 20, 61, 17))
        self.radioButton_r4_0.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r4_0.setObjectName("radioButton_r4_0")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(630, 310, 281, 61))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_r5_1 = QtWidgets.QRadioButton(parent=self.groupBox_5)
        self.radioButton_r5_1.setGeometry(QtCore.QRect(50, 20, 82, 20))
        self.radioButton_r5_1.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r5_1.setObjectName("radioButton_r5_1")
        self.radioButton_r5_0 = QtWidgets.QRadioButton(parent=self.groupBox_5)
        self.radioButton_r5_0.setGeometry(QtCore.QRect(190, 20, 82, 17))
        self.radioButton_r5_0.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.radioButton_r5_0.setObjectName("radioButton_r5_0")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(130, 520, 811, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(640, 560, 171, 21))
        self.label_11.setStyleSheet("font: 75 14pt \"Poppins\";\n"
"color: rgb(31, 31, 31);")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 120, 131, 31))
        self.label_4.setStyleSheet("color: rgb(31, 31, 31);\n"
"font: 57 12pt \"Poppins Medium\";")
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SISTEMA EXPERTO OSEO"))
        self.label_3.setText(_translate("MainWindow", "Nombre"))
        self.label_17.setText(_translate("MainWindow", "Indique sus sintomas"))
        self.label_20.setText(_translate("MainWindow", "¿Experimenta algun otro sintoma ademas del dolor? "))
        self.label_21.setText(_translate("MainWindow", "¿LLeva tiempo sintiendo el dolor?"))
        self.label_22.setText(_translate("MainWindow", "¿El dolor es fuerte?"))
        self.label_23.setText(_translate("MainWindow", "¿Tiene algun historial medico relevante?"))
        self.label_26.setText(_translate("MainWindow", "Novedades "))
        self.label_27.setText(_translate("MainWindow", "Línea de atención "))
        self.label_28.setText(_translate("MainWindow", "Nosotros "))
        self.label_29.setText(_translate("MainWindow", "Afiliaciones "))
        self.label_30.setText(_translate("MainWindow", "Empleados"))
        self.label_31.setText(_translate("MainWindow", "Red de atencion "))
        self.label_32.setText(_translate("MainWindow", "Barranquilla 0653226888"))
        self.label_33.setText(_translate("MainWindow", "Correo: Sistema_oseo@gmail.com"))
        self.label_34.setText(_translate("MainWindow", "Ley de trasnparencia"))
        self.label_35.setText(_translate("MainWindow", "Preguntas frecuentes "))
        self.label_18.setText(_translate("MainWindow", "¿Siente dolor?"))
        self.label_10.setText(_translate("MainWindow", "Filtrar nombre"))
        self.onClickBuscar.setText(_translate("MainWindow", "Buscar "))
        self.enviarDatos.setText(_translate("MainWindow", "Enviar"))
        self.radioButton_r1_0.setText(_translate("MainWindow", "No"))
        self.radioButton_r1_1.setText(_translate("MainWindow", "Sí"))
        self.radioButton_r2_1.setText(_translate("MainWindow", "Sí"))
        self.radioButton_r2_0.setText(_translate("MainWindow", "No"))
        self.radioButton_r3_1.setText(_translate("MainWindow", "Sí"))
        self.radioButton_r3_0.setText(_translate("MainWindow", "No"))
        self.radioButton_r4_1.setText(_translate("MainWindow", "Sí"))
        self.radioButton_r4_0.setText(_translate("MainWindow", "No"))
        self.radioButton_r5_1.setText(_translate("MainWindow", "Si"))
        self.radioButton_r5_0.setText(_translate("MainWindow", "No"))
        self.label_11.setText(_translate("MainWindow", "Diagnostico medico "))
        self.label_4.setText(_translate("MainWindow", "Registre usuario "))
